[package]
name = "tondi-index-processor"
description = "Tondi index processor"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tondi-consensus-core.workspace = true
tondi-consensus-notify.workspace = true
tondi-consensusmanager.workspace = true
tondi-core.workspace = true
tondi-database.workspace = true
tondi-hashes.workspace = true
tondi-index-core.workspace = true
tondi-notify.workspace = true
tondi-utils.workspace = true
tondi-utxoindex.workspace = true

async-channel.workspace = true
async-trait.workspace = true
derive_more.workspace = true
futures.workspace = true
log.workspace = true
paste.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [ "rt-multi-thread", "macros", "signal" ]}
triggered.workspace = true

[dev-dependencies]
tondi-consensus.workspace = true
parking_lot.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
rand = {workspace = true,  features = [ "small_rng" ]}