[package]
name = "spora-consensusmanager"
description = "Spora consensus library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
duration-string.workspace = true
futures-util.workspace = true
futures.workspace = true
itertools.workspace = true
spora-addresses.workspace=true
spora-consensus-core.workspace = true
spora-consensus-notify.workspace = true
spora-core.workspace = true
spora-utils.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
tokio.workspace = true
