[package]
name = "spora-p2p-mining"
description = "Spora p2p mining"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
spora-core.workspace = true
spora-consensus-core.workspace = true
spora-consensusmanager.workspace = true
spora-mining-errors.workspace = true
spora-hashes.workspace = true
spora-math.workspace = true
spora-p2p-lib.workspace = true
spora-utils.workspace = true
spora-utils-tower.workspace = true
log.workspace = true
tokio.workspace = true
