use crate::cell::{CellEntryReference, TryIntoCellEntryReferences};
use crate::imports::*;
use crate::result::Result;
use crate::tx::{generator as native, Fees, PaymentDestination, PaymentOutputs};
use crate::wasm::tx::generator::*;
use crate::wasm::tx::IFees;
use spora_exec::{CellDep, DepType, OutPoint, Script};
// use crate::wasm::wallet::Account;
use crate::wasm::CellContext;

// TODO-WASM fix outputs
#[wasm_bindgen(typescript_custom_section)]
const TS_GENERATOR_SETTINGS_OBJECT: &'static str = r#"
/**
 * CKB-compatible transaction cell dependency.
 *
 * @category Wallet SDK
 */
export interface ICellDepOutPoint {
    txHash?: Uint8Array | HexString;
    transactionId?: Uint8Array | HexString;
    tx_hash?: Uint8Array | HexString;
    index: number;
}

export interface ICellDep {
    outPoint?: ICellDepOutPoint;
    outpoint?: ICellDepOutPoint;
    out_point?: ICellDepOutPoint;
    depType?: "code" | "depGroup" | "dep_group" | "dep-group" | 0 | 1;
    dep_type?: "code" | "depGroup" | "dep_group" | "dep-group" | 0 | 1;
}

export interface ICellScriptTypeScript {
    codeHash?: Uint8Array | HexString;
    code_hash?: Uint8Array | HexString;
    hashType?: number;
    hash_type?: number;
    args?: Uint8Array | HexString;
}

export interface ICellScriptTypedCellOutput {
    outputIndex?: number;
    output_index?: number;
    index?: number;
    typeScript?: ICellScriptTypeScript;
    type_script?: ICellScriptTypeScript;
    data: Uint8Array | HexString;
}

export interface ICellScriptTypedCellResolvedCell {
    source: "Input" | "CellDep" | "input" | "cellDep" | "cell_dep" | "cell-dep";
    index: number;
    typeScript?: ICellScriptTypeScript;
    type_script?: ICellScriptTypeScript;
    data: Uint8Array | HexString;
}

/**
 * Configuration for the transaction {@link Generator}. This interface
 * allows you to specify cell sources, transaction outputs, change address,
 * priority fee, and other transaction parameters.
 *
 * If the total number of cells needed to satisfy the transaction outputs
 * exceeds maximum allowed number of cells per transaction (limited by
 * the maximum transaction mass), the {@link Generator} will produce
 * multiple chained transactions to the change address and then used these
 * transactions as a source for the "final" transaction.
 *
 * @see
 *      {@link sporaToSau},
 *      {@link Generator},
 *      {@link PendingTransaction},
 *      {@link CellContext},
 *      {@link CellEntry},
 *      {@link createTransactions},
 *      {@link estimateTransactions}
 * @category Wallet SDK
 */
interface IGeneratorSettingsObject {
    /**
     * Final transaction outputs (do not supply change transaction).
     *
     * Typical usage: { address: "spora:...", amount: 1000n }
     */
    outputs: PaymentOutput | IPaymentOutput[];
    /**
     * Address to be used for change, if any.
     */
    changeAddress: Address | string;
      /**
     * Fee rate in SAU per 1 gram of mass.
     *
     * Fee rate is applied to all transactions generated by the {@link Generator}.
     * This includes batch and final transactions. If not set, the fee rate is
     * not applied.
     */
    feeRate?: number;
    /**
     * Priority fee in SAU.
     *
     * If supplying `bigint` value, it will be interpreted as a sender-pays fee.
     * Alternatively you can supply an object with `amount` and `source` properties
     * where `source` contains the {@link FeeSource} enum.
     *
     * **IMPORTANT:* When sending an outbound transaction (transaction that
     * contains outputs), the `priorityFee` must be set, even if it is zero.
     * However, if the transaction is missing outputs (and thus you are
     * creating a compound transaction against your change address),
     * `priorityFee` should not be set (i.e. it should be `undefined`).
     *
     * @see {@link IFees}, {@link FeeSource}
     */
    priorityFee?: IFees | bigint;
    /**
     * Cell entries to be used for the transaction. This can be an
     * array of CellEntry instances, objects matching {@link ICellEntry}
     * interface, or a {@link CellContext} instance.
     */
    entries: ICellEntry[] | CellEntryReference[] | CellContext;
    /**
     * Optional cell entries that will be consumed before those available in `entries`.
     * You can use this property to apply custom input selection logic.
     * Please note that these inputs are consumed first, then `entries` are consumed
     * to generate a desirable transaction output amount.  If transaction mass
     * overflows, these inputs will be consumed into a batch/sweep transaction
     * where the destination if the `changeAddress`.
     */
    priorityEntries?: ICellEntry[] | CellEntryReference[],
    /**
     * Optional minimum number of signatures required for the transaction.
     */
    minimumSignatures?: number;
    /**
     * Optional data payload to be included in the transaction.
     */
    payload?: Uint8Array | HexString;
    /**
     * Optional header dependency hashes to include in generated transactions.
     * Each entry must be a 32-byte Uint8Array or HexString.
     */
    headerDeps?: (Uint8Array | HexString)[];
    /**
     * Optional CKB cell dependencies to include in generated transactions.
     * Use depType `"depGroup"` for standard CKB dep-group cells.
     */
    cellDeps?: ICellDep[];
    /**
     * Final transaction user output indexes that should receive a CKB built-in
     * TYPE_ID type script. Indexes refer to supplied outputs before change.
     */
    ckbTypeIdOutputs?: number[];
    /**
     * CellScript compile metadata JSON, or the parsed metadata object. When paired
     * with `cellscriptAction`, the generator applies profile-selected builder
     * side effects for that action: Spora metadata attaches the public Molecule
     * scheduler witness, while CKB metadata installs TYPE_ID scripts on planned
     * final outputs. Legacy Borsh scheduler witness fields are rejected by this
     * public generator path.
     */
    cellscriptMetadata?: string | object;
    /**
     * Action name to consume from `cellscriptMetadata`.
     */
    cellscriptAction?: string;
    /**
     * Final transaction user outputs that should become typed cells before
     * live CellScript typed-cell scheduler witness generation. Indexes refer
     * to supplied outputs before change.
     */
    cellscriptTypedCellOutputs?: ICellScriptTypedCellOutput[];
    /**
     * Resolved Input/CellDep typed cells needed for live CellScript typed-cell
     * scheduler witness generation.
     */
    cellscriptTypedCellResolvedCells?: ICellScriptTypedCellResolvedCell[];

    /**
     * Optional NetworkId or network id as string (i.e. `mainnet` or `testnet-11`). Required when {@link IGeneratorSettingsObject.entries} is array
     */
    networkId?: NetworkId | string;
}
"#;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(extends = Object, typescript_type = "IGeneratorSettingsObject")]
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub type IGeneratorSettingsObject;
}

/// Generator is a type capable of generating transactions based on a supplied
/// set of cell entries or a cell entry producer (such as {@link CellContext}). The Generator
/// accumulates cell entries until it can generate a transaction that meets the
/// requested amount or until the total mass of created inputs exceeds the allowed
/// transaction mass, at which point it will produce a compound transaction by forwarding
/// all selected cell entries to the supplied change address and prepare to start generating
/// a new transaction.  Such sequence of daisy-chained transactions is known as a "batch".
/// Each compound transaction results in a new cell, which is immediately reused in the
/// subsequent transaction.
///
/// The Generator constructor accepts a single {@link IGeneratorSettingsObject} object.
///
/// ```javascript
///
/// let generator = new Generator({
///     entries : [...],
///     changeAddress : "spora:...",
///     outputs : [
///         { amount : sporaToSau(10.0), address: "spora:..."},
///         { amount : sporaToSau(20.0), address: "spora:..."},
///         ...
///     ],
///     priorityFee : 1000n,
/// });
///
/// let pendingTransaction;
/// while(pendingTransaction = await generator.next()) {
///     await pendingTransaction.sign(privateKeys);
///     await pendingTransaction.submit(rpc);
/// }
///
/// let summary = generator.summary();
/// console.log(summary);
///
/// ```
/// @see
///     {@link IGeneratorSettingsObject},
///     {@link PendingTransaction},
///     {@link CellContext},
///     {@link createTransactions},
///     {@link estimateTransactions},
/// @category Wallet SDK
#[wasm_bindgen]
pub struct Generator {
    inner: Arc<native::Generator>,
}

#[wasm_bindgen]
impl Generator {
    #[wasm_bindgen(constructor)]
    pub fn ctor(args: IGeneratorSettingsObject) -> Result<Generator> {
        let settings = GeneratorSettings::try_from(args)?;

        let GeneratorSettings {
            network_id,
            source,
            priority_cell_entries,
            multiplexer,
            final_transaction_destination,
            change_address,
            fee_rate,
            final_priority_fee,
            minimum_signatures,
            payload,
            header_deps,
            cell_deps,
            ckb_type_id_output_indexes,
            final_cellscript_compiled_scheduler_witness,
            cellscript_typed_cell_scheduler_plan,
            cellscript_typed_cell_outputs,
            cellscript_typed_cell_resolved_cells,
        } = settings;

        let mut settings = match source {
            GeneratorSource::CellEntries(cell_entries) => {
                let change_address = change_address
                    .ok_or_else(|| Error::custom("changeAddress is required for Generator constructor with cell entries"))?;

                let network_id =
                    network_id.ok_or_else(|| Error::custom("networkId is required for Generator constructor with cell entries"))?;

                native::GeneratorSettings::try_new_with_iterator(
                    network_id,
                    Box::new(cell_entries.into_iter()),
                    priority_cell_entries,
                    change_address,
                    minimum_signatures,
                    final_transaction_destination,
                    fee_rate,
                    final_priority_fee,
                    payload,
                    multiplexer,
                )?
            }
            GeneratorSource::CellContext(cell_context) => {
                let change_address = change_address
                    .ok_or_else(|| Error::custom("changeAddress is required for Generator constructor with cell entries"))?;

                native::GeneratorSettings::try_new_with_context(
                    cell_context.into(),
                    priority_cell_entries,
                    change_address,
                    minimum_signatures,
                    final_transaction_destination,
                    final_priority_fee,
                    payload,
                    multiplexer,
                )?
            } // GeneratorSource::Account(account) => {
              //     let account: Arc<dyn crate::account::Account> = account.into();
              //     native::GeneratorSettings::try_new_with_account(account, final_transaction_destination, final_priority_fee, None)?
              // }
        }
        .with_header_deps(header_deps)
        .with_cell_deps(cell_deps)
        .with_ckb_type_id_output_indexes(ckb_type_id_output_indexes);
        settings = settings
            .with_cellscript_typed_cell_outputs(cellscript_typed_cell_outputs)
            .with_cellscript_typed_cell_resolved_cells(cellscript_typed_cell_resolved_cells);
        if let Some(plan) = cellscript_typed_cell_scheduler_plan {
            settings = settings.with_cellscript_typed_cell_scheduler_plan(plan)?;
        }
        if let Some(witness) = final_cellscript_compiled_scheduler_witness {
            settings = settings.try_with_cellscript_compiled_scheduler_witness(witness)?;
        }

        let abortable = Abortable::default();
        let generator = native::Generator::try_new(settings, None, Some(&abortable))?;

        Ok(Self { inner: Arc::new(generator) })
    }

    /// Generate next transaction
    pub async fn next(&self) -> Result<JsValue> {
        if let Some(transaction) = self.inner.generate_transaction().transpose() {
            let transaction = PendingTransaction::from(transaction?);
            Ok(transaction.into())
        } else {
            Ok(JsValue::NULL)
        }
    }

    pub async fn estimate(&self) -> Result<GeneratorSummary> {
        let mut stream = self.inner.stream();
        while stream.try_next().await?.is_some() {}
        Ok(self.summary())
    }

    pub fn summary(&self) -> GeneratorSummary {
        self.inner.summary().into()
    }
}

impl Generator {
    pub fn iter(&self) -> impl Iterator<Item = Result<native::PendingTransaction>> {
        self.inner.iter()
    }

    pub fn stream(&self) -> impl Stream<Item = Result<native::PendingTransaction>> {
        self.inner.stream()
    }
}

enum GeneratorSource {
    CellEntries(Vec<CellEntryReference>),
    CellContext(CellContext),
    // #[cfg(any(feature = "wasm32-sdk"), not(target_arch = "wasm32"))]
    // Account(Account),
}

/// Converts [`IGeneratorSettingsObject`] to a series of properties intended for use by the [`Generator`].
struct GeneratorSettings {
    pub network_id: Option<NetworkId>,
    pub source: GeneratorSource,
    pub priority_cell_entries: Option<Vec<CellEntryReference>>,
    pub multiplexer: Option<Multiplexer<Box<Events>>>,
    pub final_transaction_destination: PaymentDestination,
    pub change_address: Option<Address>,
    pub fee_rate: Option<f64>,
    pub final_priority_fee: Fees,
    pub minimum_signatures: u16,
    pub payload: Option<Vec<u8>>,
    pub header_deps: Vec<[u8; 32]>,
    pub cell_deps: Vec<CellDep>,
    pub ckb_type_id_output_indexes: Vec<usize>,
    pub final_cellscript_compiled_scheduler_witness: Option<Vec<u8>>,
    pub cellscript_typed_cell_scheduler_plan: Option<native::CellScriptTypedCellSchedulerPlan>,
    pub cellscript_typed_cell_outputs: Vec<native::CellScriptTypedCellOutput>,
    pub cellscript_typed_cell_resolved_cells: Vec<native::CellScriptTypedCellResolvedCell>,
}

impl TryFrom<IGeneratorSettingsObject> for GeneratorSettings {
    type Error = Error;
    fn try_from(args: IGeneratorSettingsObject) -> std::result::Result<Self, Self::Error> {
        let network_id = args.try_get::<NetworkId>("networkId")?;

        // lack of outputs results in a sweep transaction compounding cells into the change address
        let outputs = args.get_value("outputs")?;
        let final_transaction_destination: PaymentDestination =
            if outputs.is_undefined() { PaymentDestination::Change } else { PaymentOutputs::try_owned_from(outputs)?.into() };

        let change_address = args.try_cast_into::<Address>("changeAddress")?;

        let fee_rate = args.get_f64("feeRate").ok().and_then(|v| (v.is_finite() && !v.is_nan() && v >= 1e-8).then_some(v));

        let final_priority_fee = args.get::<IFees>("priorityFee")?.try_into()?;

        let generator_source = if let Ok(Some(context)) = args.try_cast_into::<CellContext>("entries") {
            GeneratorSource::CellContext(context)
        } else if let Some(cell_entries) = args.try_get_value("entries")? {
            GeneratorSource::CellEntries(cell_entries.try_into_cell_entry_references()?)
        } else {
            return Err(Error::custom("'entries' property is required for Generator"));
        };

        let priority_cell_entries = args.try_get_value("priorityEntries")?.map(|v| v.try_into_cell_entry_references()).transpose()?;

        let minimum_signatures = args.get_value("minimumSignatures")?;
        let minimum_signatures = if !minimum_signatures.is_undefined() {
            minimum_signatures.as_f64().expect("minimumSignatures should be a number") as u16
        } else {
            1
        };

        let payload = args.get_vec_u8("payload").ok();
        let header_deps = args.try_get_value("headerDeps")?.map(parse_header_deps).transpose()?.unwrap_or_default();
        let cell_deps = args.try_get_value("cellDeps")?.map(parse_cell_deps).transpose()?.unwrap_or_default();
        let mut ckb_type_id_output_indexes =
            args.try_get_value("ckbTypeIdOutputs")?.map(parse_ckb_type_id_output_indexes).transpose()?.unwrap_or_default();
        let cellscript_typed_cell_outputs = args
            .try_get_value("cellscriptTypedCellOutputs")?
            .map(parse_cellscript_typed_cell_outputs)
            .transpose()?
            .unwrap_or_default();
        let cellscript_typed_cell_resolved_cells = args
            .try_get_value("cellscriptTypedCellResolvedCells")?
            .map(parse_cellscript_typed_cell_resolved_cells)
            .transpose()?
            .unwrap_or_default();
        let mut final_cellscript_compiled_scheduler_witness = None;
        let mut cellscript_typed_cell_scheduler_plan = None;
        let cellscript_metadata_json = args.try_get_value("cellscriptMetadata")?.map(parse_cellscript_metadata_json).transpose()?;
        let cellscript_action = args.try_get_value("cellscriptAction")?.map(parse_cellscript_action_name).transpose()?;
        match (cellscript_metadata_json, cellscript_action) {
            (Some(metadata_json), Some(action_name)) => {
                let plan = native::cellscript_action_generator_plan_from_metadata_json(&metadata_json, &action_name)?;
                final_cellscript_compiled_scheduler_witness = plan.final_cellscript_compiled_scheduler_witness;
                ckb_type_id_output_indexes.extend(plan.ckb_type_id_output_indexes);
                cellscript_typed_cell_scheduler_plan = plan.typed_cell_scheduler_plan;
            }
            (Some(_), None) => {
                return Err(Error::custom("cellscriptAction is required when cellscriptMetadata is supplied"));
            }
            (None, Some(_)) => {
                return Err(Error::custom("cellscriptMetadata is required when cellscriptAction is supplied"));
            }
            (None, None) => {}
        }

        let settings = GeneratorSettings {
            network_id,
            source: generator_source,
            priority_cell_entries,
            multiplexer: None,
            final_transaction_destination,
            change_address,
            fee_rate,
            final_priority_fee,
            minimum_signatures,
            payload,
            header_deps,
            cell_deps,
            ckb_type_id_output_indexes,
            final_cellscript_compiled_scheduler_witness,
            cellscript_typed_cell_scheduler_plan,
            cellscript_typed_cell_outputs,
            cellscript_typed_cell_resolved_cells,
        };

        Ok(settings)
    }
}

fn parse_cellscript_metadata_json(value: JsValue) -> Result<String> {
    if let Some(metadata_json) = value.as_string() {
        if metadata_json.trim().is_empty() {
            return Err(Error::custom("cellscriptMetadata must not be empty"));
        }
        return Ok(metadata_json);
    }
    let serialized = js_sys::JSON::stringify(&value)
        .map_err(|_| Error::custom("cellscriptMetadata must be a JSON-serializable object or JSON string"))?
        .as_string()
        .ok_or_else(|| Error::custom("cellscriptMetadata must be a JSON-serializable object or JSON string"))?;
    if serialized.trim().is_empty() || serialized == "null" {
        return Err(Error::custom("cellscriptMetadata must be a JSON object or JSON string"));
    }
    Ok(serialized)
}

fn parse_cellscript_action_name(value: JsValue) -> Result<String> {
    let action_name = value.as_string().ok_or_else(|| Error::custom("cellscriptAction must be a string"))?;
    if action_name.trim().is_empty() {
        return Err(Error::custom("cellscriptAction must not be empty"));
    }
    Ok(action_name)
}

fn parse_ckb_type_id_output_indexes(value: JsValue) -> Result<Vec<usize>> {
    if !Array::is_array(&value) {
        return Err(Error::custom("ckbTypeIdOutputs must be an array"));
    }

    let array = Array::from(&value);
    let mut output_indexes = Vec::with_capacity(array.length() as usize);
    for (index, value) in array.iter().enumerate() {
        let raw = value.as_f64().ok_or_else(|| Error::custom(format!("ckbTypeIdOutputs[{index}] must be a non-negative integer")))?;
        if !raw.is_finite() || raw.fract() != 0.0 || raw < 0.0 {
            return Err(Error::custom(format!("ckbTypeIdOutputs[{index}] must be a non-negative integer")));
        }
        output_indexes.push(raw as usize);
    }
    Ok(output_indexes)
}

fn parse_cellscript_typed_cell_outputs(value: JsValue) -> Result<Vec<native::CellScriptTypedCellOutput>> {
    if !Array::is_array(&value) {
        return Err(Error::custom("cellscriptTypedCellOutputs must be an array"));
    }

    let array = Array::from(&value);
    let mut typed_outputs = Vec::with_capacity(array.length() as usize);
    for (index, value) in array.iter().enumerate() {
        typed_outputs.push(parse_cellscript_typed_cell_output(value, index)?);
    }
    Ok(typed_outputs)
}

fn parse_cellscript_typed_cell_output(value: JsValue, index: usize) -> Result<native::CellScriptTypedCellOutput> {
    let context = format!("cellscriptTypedCellOutputs[{index}]");
    let object = Object::try_from(&value).ok_or_else(|| Error::custom(format!("{context} must be an object")))?;
    let output_index_value = object_try_get_any(&object, &["outputIndex", "output_index", "index"])?
        .ok_or_else(|| Error::custom(format!("{context}.outputIndex is required")))?;
    let output_index = parse_usize_value(output_index_value, &format!("{context}.outputIndex"))?;
    let type_script_value = object_try_get_any(&object, &["typeScript", "type_script"])?
        .ok_or_else(|| Error::custom(format!("{context}.typeScript is required")))?;
    let type_script = parse_cellscript_type_script(type_script_value, &format!("{context}.typeScript"))?;
    let data_value = object.get_value("data")?;
    if data_value.is_undefined() {
        return Err(Error::custom(format!("{context}.data is required")));
    }
    let data = data_value.try_as_vec_u8().map_err(|err| Error::custom(format!("{context}.data: {err}")))?;
    Ok(native::CellScriptTypedCellOutput::new(output_index, type_script, data))
}

fn parse_cellscript_typed_cell_resolved_cells(value: JsValue) -> Result<Vec<native::CellScriptTypedCellResolvedCell>> {
    if !Array::is_array(&value) {
        return Err(Error::custom("cellscriptTypedCellResolvedCells must be an array"));
    }

    let array = Array::from(&value);
    let mut resolved_cells = Vec::with_capacity(array.length() as usize);
    for (index, value) in array.iter().enumerate() {
        resolved_cells.push(parse_cellscript_typed_cell_resolved_cell(value, index)?);
    }
    Ok(resolved_cells)
}

fn parse_cellscript_typed_cell_resolved_cell(value: JsValue, index: usize) -> Result<native::CellScriptTypedCellResolvedCell> {
    let context = format!("cellscriptTypedCellResolvedCells[{index}]");
    let object = Object::try_from(&value).ok_or_else(|| Error::custom(format!("{context} must be an object")))?;
    let source_value = object.get_value("source")?;
    if source_value.is_undefined() {
        return Err(Error::custom(format!("{context}.source is required")));
    }
    let source = parse_cellscript_typed_cell_source(source_value, &format!("{context}.source"))?;
    let index_value = object.get_value("index")?;
    if index_value.is_undefined() {
        return Err(Error::custom(format!("{context}.index is required")));
    }
    let cell_index = parse_usize_value(index_value, &format!("{context}.index"))?;
    let type_script_value = object_try_get_any(&object, &["typeScript", "type_script"])?
        .ok_or_else(|| Error::custom(format!("{context}.typeScript is required")))?;
    let type_script = parse_cellscript_type_script(type_script_value, &format!("{context}.typeScript"))?;
    let data_value = object.get_value("data")?;
    if data_value.is_undefined() {
        return Err(Error::custom(format!("{context}.data is required")));
    }
    let data = data_value.try_as_vec_u8().map_err(|err| Error::custom(format!("{context}.data: {err}")))?;
    match source.as_str() {
        "Input" => Ok(native::CellScriptTypedCellResolvedCell::input(cell_index, type_script, data)),
        "CellDep" => Ok(native::CellScriptTypedCellResolvedCell::cell_dep(cell_index, type_script, data)),
        _ => unreachable!("typed-cell source parser only returns supported sources"),
    }
}

fn parse_cellscript_typed_cell_source(value: JsValue, context: &str) -> Result<String> {
    let source = value.as_string().ok_or_else(|| Error::custom(format!("{context} must be 'Input' or 'CellDep'")))?;
    let normalized = source.trim().to_ascii_lowercase().replace('_', "").replace('-', "").replace(' ', "");
    match normalized.as_str() {
        "input" => Ok("Input".to_string()),
        "celldep" => Ok("CellDep".to_string()),
        _ => Err(Error::custom(format!("{context} must be 'Input' or 'CellDep'"))),
    }
}

fn parse_cellscript_type_script(value: JsValue, context: &str) -> Result<Script> {
    let object = Object::try_from(&value).ok_or_else(|| Error::custom(format!("{context} must be an object")))?;
    let code_hash_value = object_try_get_any(&object, &["codeHash", "code_hash"])?
        .ok_or_else(|| Error::custom(format!("{context}.codeHash is required")))?;
    let code_hash_bytes = code_hash_value.try_as_vec_u8().map_err(|err| Error::custom(format!("{context}.codeHash: {err}")))?;
    let code_hash = code_hash_bytes
        .as_slice()
        .try_into()
        .map_err(|_| Error::custom(format!("{context}.codeHash must be exactly 32 bytes, got {}", code_hash_bytes.len())))?;
    let hash_type_value = object_try_get_any(&object, &["hashType", "hash_type"])?
        .ok_or_else(|| Error::custom(format!("{context}.hashType is required")))?;
    let hash_type = parse_u8_value(hash_type_value, &format!("{context}.hashType"))?;
    let args = match object.get_value("args")? {
        value if value.is_undefined() => Vec::new(),
        value => value.try_as_vec_u8().map_err(|err| Error::custom(format!("{context}.args: {err}")))?,
    };
    Ok(Script::new(code_hash, hash_type, args))
}

fn parse_header_deps(value: JsValue) -> Result<Vec<[u8; 32]>> {
    if !Array::is_array(&value) {
        return Err(Error::custom("headerDeps must be an array"));
    }

    let array = Array::from(&value);
    let mut header_deps = Vec::with_capacity(array.length() as usize);
    for (index, value) in array.iter().enumerate() {
        let bytes = value.try_as_vec_u8().map_err(|err| Error::custom(format!("headerDeps[{index}]: {err}")))?;
        let hash = bytes
            .as_slice()
            .try_into()
            .map_err(|_| Error::custom(format!("headerDeps[{index}] must be exactly 32 bytes, got {}", bytes.len())))?;
        header_deps.push(hash);
    }
    Ok(header_deps)
}

fn parse_cell_deps(value: JsValue) -> Result<Vec<CellDep>> {
    if !Array::is_array(&value) {
        return Err(Error::custom("cellDeps must be an array"));
    }

    let array = Array::from(&value);
    let mut cell_deps = Vec::with_capacity(array.length() as usize);
    for (index, value) in array.iter().enumerate() {
        cell_deps.push(parse_cell_dep(value, index)?);
    }
    Ok(cell_deps)
}

fn parse_cell_dep(value: JsValue, index: usize) -> Result<CellDep> {
    let context = format!("cellDeps[{index}]");
    let object = Object::try_from(&value).ok_or_else(|| Error::custom(format!("{context} must be an object")))?;
    let out_point_value = object_try_get_any(&object, &["outPoint", "outpoint", "out_point"])?
        .ok_or_else(|| Error::custom(format!("{context}.outPoint is required")))?;
    let dep_type_value = object_try_get_any(&object, &["depType", "dep_type"])?
        .ok_or_else(|| Error::custom(format!("{context}.depType is required")))?;
    let out_point = parse_out_point(out_point_value, &format!("{context}.outPoint"))?;
    let dep_type = parse_dep_type(dep_type_value, &format!("{context}.depType"))?;
    Ok(CellDep { out_point, dep_type })
}

fn parse_out_point(value: JsValue, context: &str) -> Result<OutPoint> {
    let object = Object::try_from(&value).ok_or_else(|| Error::custom(format!("{context} must be an object")))?;
    let tx_hash_value = object_try_get_any(&object, &["txHash", "transactionId", "tx_hash"])?
        .ok_or_else(|| Error::custom(format!("{context}.txHash is required")))?;
    let bytes = tx_hash_value.try_as_vec_u8().map_err(|err| Error::custom(format!("{context}.txHash: {err}")))?;
    let tx_hash = bytes
        .as_slice()
        .try_into()
        .map_err(|_| Error::custom(format!("{context}.txHash must be exactly 32 bytes, got {}", bytes.len())))?;
    let index_value = object.get_value("index")?;
    if index_value.is_undefined() {
        return Err(Error::custom(format!("{context}.index is required")));
    }
    let index = parse_u32_value(index_value, &format!("{context}.index"))?;
    Ok(OutPoint::new(tx_hash, index))
}

fn parse_dep_type(value: JsValue, context: &str) -> Result<DepType> {
    if let Some(dep_type) = value.as_string() {
        let normalized = dep_type.trim().to_ascii_lowercase().replace('_', "").replace('-', "").replace(' ', "");
        return match normalized.as_str() {
            "code" | "0" => Ok(DepType::Code),
            "depgroup" | "1" => Ok(DepType::DepGroup),
            _ => Err(Error::custom(format!("{context} must be 'code'/'depGroup' or 0/1"))),
        };
    }

    let raw = value.as_f64().ok_or_else(|| Error::custom(format!("{context} must be 'code'/'depGroup' or 0/1")))?;
    if !raw.is_finite() || raw.fract() != 0.0 {
        return Err(Error::custom(format!("{context} must be 'code'/'depGroup' or 0/1")));
    }
    match raw as u8 {
        0 if raw == 0.0 => Ok(DepType::Code),
        1 if raw == 1.0 => Ok(DepType::DepGroup),
        _ => Err(Error::custom(format!("{context} must be 'code'/'depGroup' or 0/1"))),
    }
}

fn parse_u32_value(value: JsValue, context: &str) -> Result<u32> {
    let raw = value.as_f64().ok_or_else(|| Error::custom(format!("{context} must be a non-negative u32 integer")))?;
    if !raw.is_finite() || raw.fract() != 0.0 || raw < 0.0 || raw > u32::MAX as f64 {
        return Err(Error::custom(format!("{context} must be a non-negative u32 integer")));
    }
    Ok(raw as u32)
}

fn parse_u8_value(value: JsValue, context: &str) -> Result<u8> {
    let raw = value.as_f64().ok_or_else(|| Error::custom(format!("{context} must be a non-negative u8 integer")))?;
    if !raw.is_finite() || raw.fract() != 0.0 || raw < 0.0 || raw > u8::MAX as f64 {
        return Err(Error::custom(format!("{context} must be a non-negative u8 integer")));
    }
    Ok(raw as u8)
}

fn parse_usize_value(value: JsValue, context: &str) -> Result<usize> {
    let raw = value.as_f64().ok_or_else(|| Error::custom(format!("{context} must be a non-negative integer")))?;
    if !raw.is_finite() || raw.fract() != 0.0 || raw < 0.0 || raw > usize::MAX as f64 {
        return Err(Error::custom(format!("{context} must be a non-negative integer")));
    }
    Ok(raw as usize)
}

fn object_try_get_any(object: &Object, keys: &[&str]) -> Result<Option<JsValue>> {
    for key in keys {
        if let Some(value) = object.try_get_value(key)? {
            return Ok(Some(value));
        }
    }
    Ok(None)
}
