[package]
name = "spora-rpc-core"
description = "Spora RPC core"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm32-sdk = [
    "spora-consensus-client/wasm32-sdk",
    "spora-consensus-wasm/wasm32-sdk"
]

[dependencies]
spora-addresses.workspace = true
spora-consensus-core.workspace = true
spora-consensus-client.workspace = true
spora-consensus-notify.workspace = true
spora-consensus-wasm.workspace = true
spora-core.workspace = true
spora-hashes.workspace = true
spora-index-core.workspace = true
spora-math.workspace = true
spora-mining-errors.workspace = true
spora-notify.workspace = true
spora-txscript.workspace = true
spora-utils.workspace = true
spora-rpc-macros.workspace = true

async-channel.workspace = true
async-trait.workspace = true
borsh.workspace = true
blake3.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
downcast.workspace = true
faster-hex.workspace = true
hex.workspace = true
js-sys.workspace = true
log.workspace = true
paste.workspace = true
rand.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
uuid.workspace = true
wasm-bindgen.workspace = true
workflow-core.workspace = true
workflow-serializer.workspace = true
workflow-wasm.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
