[package]
name = "tondi-rpc-core"
description = "Tondi RPC core"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm32-sdk = [
    "tondi-consensus-client/wasm32-sdk",
    "tondi-consensus-wasm/wasm32-sdk"
]

[dependencies]
tondi-addresses.workspace = true
tondi-consensus-core.workspace = true
tondi-consensus-client.workspace = true
tondi-consensus-notify.workspace = true
tondi-consensus-wasm.workspace = true
tondi-core.workspace = true
tondi-hashes.workspace = true
tondi-index-core.workspace = true
tondi-math.workspace = true
tondi-mining-errors.workspace = true
tondi-notify.workspace = true
tondi-txscript.workspace = true
tondi-utils.workspace = true
tondi-rpc-macros.workspace = true

async-channel.workspace = true
async-trait.workspace = true
borsh.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
downcast.workspace = true
faster-hex.workspace = true
hex.workspace = true
js-sys.workspace = true
log.workspace = true
paste.workspace = true
rand.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
uuid.workspace = true
wasm-bindgen.workspace = true
workflow-core.workspace = true
workflow-serializer.workspace = true
workflow-wasm.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
