#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Spora WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora-keygen ./build/docs/spora-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Spora WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora-rpc ./build/docs/spora-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Spora WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora-core ./build/docs/spora-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Spora WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora ./build/docs/spora.ts
else
    echo "building keygen"
    typedoc --name "Spora WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora-keygen ./build/docs/spora-keygen.ts
    echo "building rpc"
    typedoc --name "Spora WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora-rpc ./build/docs/spora-rpc.ts
    echo "building core"
    typedoc --name "Spora WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora-core ./build/docs/spora-core.ts
    echo "building full"
    typedoc --name "Spora WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/spora ./build/docs/spora.ts

fi