#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Tondi WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi-keygen ./build/docs/tondi-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Tondi WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi-rpc ./build/docs/tondi-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Tondi WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi-core ./build/docs/tondi-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Tondi WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi ./build/docs/tondi.ts
else
    echo "building keygen"
    typedoc --name "Tondi WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi-keygen ./build/docs/tondi-keygen.ts
    echo "building rpc"
    typedoc --name "Tondi WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi-rpc ./build/docs/tondi-rpc.ts
    echo "building core"
    typedoc --name "Tondi WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi-core ./build/docs/tondi-core.ts
    echo "building full"
    typedoc --name "Tondi WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/tondi ./build/docs/tondi.ts

fi