#!/bin/bash
# This script builds the Rusty Spora WASM32 SDK release.

# make the script fail for any failed command
set -e

# FIX: https://github.com/rust-lang/rust/issues/141048
export RUSTFLAGS=-Ctarget-cpu=mvp

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/spora-wasm32-sdk/web
mkdir -p release/spora-wasm32-sdk/nodejs
mkdir -p release/spora-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name spora-rpc --out-dir web/spora-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name spora --out-dir web/spora-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name spora --out-dir web/spora-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name spora --out-dir web/spora-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name spora --out-dir web/spora-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name spora --out-dir web/spora-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name spora --out-dir web/spora-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name spora --out-dir web/spora --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name spora --out-dir web/spora-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name spora --out-dir nodejs/spora --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name spora --out-dir nodejs/spora-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name spora --out-dir build/docs/spora --features wasm32-sdk $@
typedoc --name "Spora WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spora-keygen ./build/docs/spora-keygen.ts
typedoc --name "Spora WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spora-rpc ./build/docs/spora-rpc.ts
typedoc --name "Spora WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spora-core ./build/docs/spora-core.ts
typedoc --name "Spora WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/spora ./build/docs/spora.ts

# cp -r ../rpc/wrpc/wasm/web/spora-rpc release/spora-wasm32-sdk/web/spora-rpc
cp -r web/spora-keygen release/spora-wasm32-sdk/web/spora-keygen
cp -r web/spora-keygen-dev release/spora-wasm32-sdk/web/spora-keygen-dev

cp -r web/spora-rpc release/spora-wasm32-sdk/web/spora-rpc
cp -r web/spora-rpc-dev release/spora-wasm32-sdk/web/spora-rpc-dev

cp -r web/spora-core release/spora-wasm32-sdk/web/spora-core
cp -r web/spora-core-dev release/spora-wasm32-sdk/web/spora-core-dev

cp -r web/spora release/spora-wasm32-sdk/web/spora
cp -r web/spora-dev release/spora-wasm32-sdk/web/spora-dev

cp -r nodejs/spora release/spora-wasm32-sdk/nodejs/spora
cp -r nodejs/spora-dev release/spora-wasm32-sdk/nodejs/spora-dev

cp -r docs/spora-keygen release/spora-wasm32-sdk/docs/spora-keygen
cp -r docs/spora-rpc release/spora-wasm32-sdk/docs/spora-rpc
cp -r docs/spora-core release/spora-wasm32-sdk/docs/spora-core
cp -r docs/spora release/spora-wasm32-sdk/docs/spora

mkdir -p release/spora-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/spora-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/spora-wasm32-sdk/examples/
cp -r examples/web release/spora-wasm32-sdk/examples/
cp -r examples/init.js release/spora-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/spora-wasm32-sdk/examples/
cp -r examples/package.json release/spora-wasm32-sdk/examples/

pushd .
cd release/spora-wasm32-sdk/examples
npm install
popd

# tsc release/spora-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/spora-wasm32-sdk/index.html
cp README.md release/spora-wasm32-sdk/README.md
cp CHANGELOG.md release/spora-wasm32-sdk/CHANGELOG.md
cp LICENSE release/spora-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/spora-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r spora-wasm32-sdk.zip spora-wasm32-sdk
popd
