#!/bin/bash
set -e

# FIX: https://github.com/rust-lang/rust/issues/141048
export RUSTFLAGS=-Ctarget-cpu=mvp

wasm-pack build --weak-refs --target nodejs --out-name spora --out-dir nodejs/spora --features wasm32-sdk
