#!/bin/bash
# This script builds the Rusty Tondi WASM32 SDK release.

# make the script fail for any failed command
set -e

# FIX: https://github.com/rust-lang/rust/issues/141048
export RUSTFLAGS=-Ctarget-cpu=mvp

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/tondi-wasm32-sdk/web
mkdir -p release/tondi-wasm32-sdk/nodejs
mkdir -p release/tondi-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name tondi-rpc --out-dir web/tondi-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name tondi --out-dir web/tondi-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name tondi --out-dir web/tondi-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name tondi --out-dir web/tondi-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name tondi --out-dir web/tondi-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name tondi --out-dir web/tondi-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name tondi --out-dir web/tondi-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name tondi --out-dir web/tondi --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name tondi --out-dir web/tondi-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name tondi --out-dir nodejs/tondi --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name tondi --out-dir nodejs/tondi-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name tondi --out-dir build/docs/tondi --features wasm32-sdk $@
typedoc --name "Tondi WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/tondi-keygen ./build/docs/tondi-keygen.ts
typedoc --name "Tondi WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/tondi-rpc ./build/docs/tondi-rpc.ts
typedoc --name "Tondi WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/tondi-core ./build/docs/tondi-core.ts
typedoc --name "Tondi WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/tondi ./build/docs/tondi.ts

# cp -r ../rpc/wrpc/wasm/web/tondi-rpc release/tondi-wasm32-sdk/web/tondi-rpc
cp -r web/tondi-keygen release/tondi-wasm32-sdk/web/tondi-keygen
cp -r web/tondi-keygen-dev release/tondi-wasm32-sdk/web/tondi-keygen-dev

cp -r web/tondi-rpc release/tondi-wasm32-sdk/web/tondi-rpc
cp -r web/tondi-rpc-dev release/tondi-wasm32-sdk/web/tondi-rpc-dev

cp -r web/tondi-core release/tondi-wasm32-sdk/web/tondi-core
cp -r web/tondi-core-dev release/tondi-wasm32-sdk/web/tondi-core-dev

cp -r web/tondi release/tondi-wasm32-sdk/web/tondi
cp -r web/tondi-dev release/tondi-wasm32-sdk/web/tondi-dev

cp -r nodejs/tondi release/tondi-wasm32-sdk/nodejs/tondi
cp -r nodejs/tondi-dev release/tondi-wasm32-sdk/nodejs/tondi-dev

cp -r docs/tondi-keygen release/tondi-wasm32-sdk/docs/tondi-keygen
cp -r docs/tondi-rpc release/tondi-wasm32-sdk/docs/tondi-rpc
cp -r docs/tondi-core release/tondi-wasm32-sdk/docs/tondi-core
cp -r docs/tondi release/tondi-wasm32-sdk/docs/tondi

mkdir -p release/tondi-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/tondi-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/tondi-wasm32-sdk/examples/
cp -r examples/web release/tondi-wasm32-sdk/examples/
cp -r examples/init.js release/tondi-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/tondi-wasm32-sdk/examples/
cp -r examples/package.json release/tondi-wasm32-sdk/examples/

pushd .
cd release/tondi-wasm32-sdk/examples
npm install
popd

# tsc release/tondi-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/tondi-wasm32-sdk/index.html
cp README.md release/tondi-wasm32-sdk/README.md
cp CHANGELOG.md release/tondi-wasm32-sdk/CHANGELOG.md
cp LICENSE release/tondi-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/tondi-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r tondi-wasm32-sdk.zip tondi-wasm32-sdk
popd
