[package]
name = "spora-wasm"
description = "spora WASM bindings"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
repository.workspace = true
# wasm-pack requires this value to be a string
# (it can not be derived from the workspace)
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if.workspace = true
js-sys.workspace = true
spora-addresses.workspace = true
spora-bip32.workspace = true
spora-consensus-core.workspace = true
spora-consensus-wasm.workspace = true
spora-core.workspace = true
spora-math.workspace = true
spora-pow.workspace = true
spora-rpc-core.workspace = true
spora-utils.workspace = true
spora-wasm-core.workspace = true
spora-wallet-core.workspace = true
spora-wallet-keys.workspace = true
spora-wrpc-client.workspace = true
spora-wrpc-wasm.workspace = true
num.workspace = true
wasm-bindgen.workspace = true
workflow-log.workspace = true
workflow-core.workspace = true
workflow-wasm.workspace = true

[features] 
wasm32-sdk = [
    "spora-wallet-core/wasm32-sdk",
    "spora-pow/wasm32-sdk",
]
wasm32-core = [
    "spora-wallet-core/wasm32-core",
    "spora-pow/wasm32-sdk",
]
wasm32-rpc = [
    "spora-consensus-core/wasm32-sdk",
    "spora-consensus-wasm/wasm32-sdk",
    "spora-wrpc-client/wasm32-sdk",
    "spora-wrpc-wasm/wasm32-sdk",
]
wasm32-keygen = []
default = []

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]

[package.metadata.emanate.wasm]
targets = [
    { target = "nodejs", out-dir = "nodejs/spora" },
    { target = "web", out-dir = "web/spora" }
]
folder = "setup"

# Workaround for Rust 1.87.0
# https://github.com/rust-lang/rust/issues/141048
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O","--enable-bulk-memory"]
