[package]
name = "tondi-wasm"
description = "tondi WASM bindings"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
repository.workspace = true
# wasm-pack requires this value to be a string
# (it can not be derived from the workspace)
license = "ISC"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if.workspace = true
js-sys.workspace = true
tondi-addresses.workspace = true
tondi-bip32.workspace = true
tondi-consensus-core.workspace = true
tondi-consensus-wasm.workspace = true
tondi-core.workspace = true
tondi-math.workspace = true
tondi-pow.workspace = true
tondi-txscript.workspace = true
tondi-rpc-core.workspace = true
tondi-utils.workspace = true
tondi-wasm-core.workspace = true
tondi-wallet-core.workspace = true
tondi-wallet-keys.workspace = true
tondi-wrpc-client.workspace = true
tondi-wrpc-wasm.workspace = true
num.workspace = true
wasm-bindgen.workspace = true
workflow-log.workspace = true
workflow-core.workspace = true
workflow-wasm.workspace = true

[features] 
wasm32-sdk = [
    "tondi-wallet-core/wasm32-sdk",
    "tondi-pow/wasm32-sdk",
    "tondi-txscript/wasm32-sdk",
]
wasm32-core = [
    "tondi-wallet-core/wasm32-core",
    "tondi-pow/wasm32-sdk",
    "tondi-txscript/wasm32-sdk",
]
wasm32-rpc = [
    "tondi-consensus-core/wasm32-sdk",
    "tondi-consensus-wasm/wasm32-sdk",
    "tondi-wrpc-client/wasm32-sdk",
    "tondi-wrpc-wasm/wasm32-sdk",
]
wasm32-keygen = []
default = []

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]

[package.metadata.emanate.wasm]
targets = [
    { target = "nodejs", out-dir = "nodejs/tondi" },
    { target = "web", out-dir = "web/tondi" }
]
folder = "setup"
