[[resolver]]
enable = false
address = "http://127.0.0.1:8888"

[[group]]
template = "https://*.tondi.org"
nodes = ["explorer"]

# [[group]]
# template = "https://*.tondi.red"
# nodes = ["john", "mike", "paul", "alex"]

# [[group]]
# template = "https://*.tondi.green"
# nodes = ["jake", "mark", "adam", "liam"]

# [[group]]
# template = "https://*.tondi.blue"
# nodes = ["noah", "ryan", "jack", "luke"]

# [[group]]
# enable = true
# template = "https://*.tondi-ng.org"
# nodes = ["cole", "ivan", "oscar", "zane"]

# [[group]]
# enable = true
# template = "https://*.tondi-ng.io"
# nodes = ["gary", "hugo", "finn", "evan"]

# [[group]]
# enable = true
# template = "https://*.tondi-ng.net"
# nodes = ["neil", "dave", "kyle", "toby"]

# ---

# [[group]]
# enable = false
# template = "https://*."
# nodes = ["rudy", "todd", "clay", "walt"]
