[package]
name = "tondi-p2p-flows"
description = "Tondi p2p flows"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tondi-core.workspace = true
tondi-consensus-core.workspace = true
tondi-consensus-notify.workspace = true
tondi-p2p-lib.workspace = true
tondi-utils.workspace = true
tondi-utils-tower.workspace = true
tondi-hashes.workspace = true
tondi-muhash.workspace = true
tondi-connectionmanager.workspace = true
tondi-addressmanager.workspace = true
tondi-consensusmanager.workspace = true
tondi-mining.workspace = true
tondi-notify.workspace = true

async-trait.workspace = true
futures = { workspace = true, features = ["alloc"] }
indexmap.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = { workspace = true, features = ["net"] }
uuid = { workspace = true, features = ["v4", "fast-rng"] }
chrono.workspace = true
