[package]
name = "spora-consensus-core"
description = "Spora consensus core"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
devnet-prealloc = []
wasm32-sdk = []
default = []

[dependencies]
arc-swap.workspace = true
async-trait.workspace = true
bitcoin.workspace = true
blake3.workspace = true
borsh.workspace = true
cfg-if.workspace = true
faster-hex.workspace = true
futures-util.workspace = true
getrandom.workspace = true
itertools.workspace = true
js-sys.workspace = true
log.workspace = true
spora-addresses.workspace = true
spora-core.workspace = true
spora-exec.workspace = true
spora-hashes.workspace = true
spora-math.workspace = true
spora-merkle.workspace = true
spora-muhash.workspace = true
spora-txscript-errors.workspace = true
spora-utils.workspace = true
rand.workspace = true
secp256k1.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-serializer.workspace = true
workflow-wasm.workspace = true
hex = "0.4.3"
serde_bytes = "0.11.17"

[dev-dependencies]
criterion.workspace = true
bincode.workspace = true
wasm-bindgen-test.workspace = true
web-sys.workspace = true
insta.workspace = true

[[bench]]
name = "serde_benchmark"
harness = false

[lints]
workspace = true
