[package]
name = "tondi-rpc-service"
description = "Tondi RPC service"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tondi-addresses.workspace = true
tondi-consensus-core.workspace = true
tondi-consensus-notify.workspace = true
tondi-consensusmanager.workspace = true
tondi-core.workspace = true
tondi-hashes.workspace = true
tondi-index-core.workspace = true
tondi-math.workspace = true
tondi-mining.workspace = true
tondi-notify.workspace = true
tondi-p2p-flows.workspace = true
tondi-p2p-lib.workspace = true
tondi-p2p-mining.workspace = true
tondi-perf-monitor.workspace = true
tondi-rpc-core.workspace = true
tondi-txscript.workspace = true
tondi-utils.workspace = true
tondi-utils-tower.workspace = true

async-trait.workspace = true
log.workspace = true
tokio.workspace = true
triggered.workspace = true
workflow-rpc.workspace = true