[package]
name = "spora-rpc-service"
description = "Spora RPC service"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
spora-addresses.workspace = true
spora-cellindex.workspace = true
spora-consensus-client.workspace = true
spora-consensus-core.workspace = true
spora-consensus-notify.workspace = true
spora-consensusmanager.workspace = true
spora-core.workspace = true
spora-exec.workspace = true
spora-hashes.workspace = true
spora-index-core.workspace = true
spora-math.workspace = true
spora-mining.workspace = true
spora-notify.workspace = true
spora-p2p-flows.workspace = true
spora-p2p-lib.workspace = true
spora-p2p-mining.workspace = true
spora-perf-monitor.workspace = true
spora-rpc-core.workspace = true
spora-state.workspace = true
spora-utils.workspace = true
spora-utils-tower.workspace = true

async-trait.workspace = true
log.workspace = true
tokio.workspace = true
triggered.workspace = true
workflow-rpc.workspace = true
