[package]
name = "tondi-consensus"
description = "Tondi consensus library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arc-swap.workspace = true
async-channel.workspace = true
bincode.workspace = true
borsh.workspace = true
crossbeam-channel.workspace = true
faster-hex.workspace = true
futures-util.workspace = true
indexmap.workspace = true
itertools.workspace = true
tondi-addresses.workspace = true
tondi-consensus-core.workspace = true
tondi-consensus-notify.workspace = true
tondi-consensusmanager.workspace = true
tondi-core.workspace = true
tondi-database.workspace = true
tondi-exec = { path = "../exec", version = "1.21.0" }
tondi-hashes.workspace = true
tondi-state = { path = "../state", version = "1.21.0" }
tondi-math.workspace = true
tondi-merkle.workspace = true
tondi-muhash.workspace = true
tondi-notify.workspace = true
tondi-pow.workspace = true
tondi-txscript.workspace = true
tondi-txscript-errors.workspace = true
tondi-utils.workspace = true
log.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
rayon.workspace = true
rocksdb.workspace = true
secp256k1.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tokio.workspace = true
hex = "0.4"

rand = { workspace = true, features = ["small_rng"] }
blake3 = "1.8.2"
time = "0.3.41"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies]
criterion.workspace = true
serde_json.workspace = true
flate2.workspace = true
rand_distr.workspace = true
tondi-txscript-errors.workspace = true
tondi-addresses.workspace = true

[[bench]]
name = "parallel_muhash"
harness = false

[[bench]]
name = "check_scripts"
harness = false

[features]
html_reports = []
devnet-prealloc = ["tondi-consensus-core/devnet-prealloc"]
