[package]
name = "spora-consensus"
description = "Spora consensus library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arc-swap.workspace = true
async-channel.workspace = true
bincode.workspace = true
borsh.workspace = true
crossbeam-channel.workspace = true
faster-hex.workspace = true
futures-util.workspace = true
indexmap.workspace = true
itertools.workspace = true
spora-addresses.workspace = true
spora-consensus-core.workspace = true
spora-consensus-notify.workspace = true
spora-consensusmanager.workspace = true
spora-core.workspace = true
spora-database.workspace = true
spora-exec = { path = "../exec", version = "1.21.0" }
spora-hashes.workspace = true
spora-state = { path = "../state", version = "1.21.0" }
spora-math.workspace = true
spora-merkle.workspace = true
spora-muhash.workspace = true
spora-notify.workspace = true
spora-pow.workspace = true
spora-utils.workspace = true
log.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
rayon.workspace = true
rocksdb.workspace = true
secp256k1.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tokio.workspace = true
hex = "0.4"

rand = { workspace = true, features = ["small_rng"] }
blake3 = "1.8.2"
time = "0.3.41"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies]
criterion.workspace = true
serde_json.workspace = true
flate2.workspace = true
rand_distr.workspace = true
spora-addresses.workspace = true

[[bench]]
name = "parallel_muhash"
harness = false

[features]
html_reports = []
devnet-prealloc = ["spora-consensus-core/devnet-prealloc"]
vm = ["spora-exec/vm"]
