[package]
name = "spora-mining"
description = "Spora mining"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
spora-addresses.workspace = true
spora-consensus-core.workspace = true
spora-consensusmanager.workspace = true
spora-core.workspace = true
spora-hashes.workspace = true
spora-mempool.workspace = true
spora-mining-errors.workspace = true
spora-muhash.workspace = true
spora-utils.workspace = true

futures-util.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true
smallvec.workspace = true
sweep-bptree = "0.4.1"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
blake3.workspace = true

[dev-dependencies]
criterion.workspace = true
secp256k1.workspace = true

[[bench]]
name = "bench"
harness = false
