[package]
name = "tondi-mining"
description = "Tondi mining"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tondi-addresses.workspace = true
tondi-consensus-core.workspace = true
tondi-consensusmanager.workspace = true
tondi-core.workspace = true
tondi-hashes.workspace = true
tondi-mining-errors.workspace = true
tondi-muhash.workspace = true
tondi-txscript.workspace = true
tondi-utils.workspace = true

futures-util.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true
smallvec.workspace = true
sweep-bptree = "0.4.1"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }

[dev-dependencies]
tondi-txscript.workspace = true
criterion.workspace = true
secp256k1.workspace = true

[[bench]]
name = "bench"
harness = false
