[package]
name = "sporad"
description = "spora full node daemon"
keywords = ["spora", "blockdag"]
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "sporad_lib"
crate-type = ["cdylib", "lib"]

[dependencies]
spora-alloc.workspace = true # This changes the global allocator for all of the next dependencies so should be kept first

spora-addresses.workspace = true
spora-addressmanager.workspace = true
spora-cellindex.workspace = true
spora-consensus-core.workspace = true
spora-consensus-notify.workspace = true
spora-consensus.workspace = true
spora-consensusmanager.workspace = true
spora-core.workspace = true
spora-database.workspace = true
spora-grpc-server.workspace = true
spora-hashes.workspace = true
spora-index-processor.workspace = true
spora-mining.workspace = true
spora-notify.workspace = true
spora-p2p-flows.workspace = true
spora-p2p-lib.workspace = true
spora-p2p-mining.workspace = true
spora-perf-monitor.workspace = true
spora-rpc-core.workspace = true
spora-rpc-service.workspace = true
spora-utils.workspace = true
spora-utils-tower.workspace = true
spora-wrpc-server.workspace = true

async-channel.workspace = true
cfg-if.workspace = true
clap.workspace = true
dhat = { workspace = true, optional = true }
dirs.workspace = true
futures-util.workspace = true
itertools.workspace = true
log.workspace = true
num_cpus.workspace = true
rand.workspace = true
rayon.workspace = true
rocksdb.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
workflow-log.workspace = true

toml = "0.8.10"
serde_with = "3.7.0"

[features]
heap = ["dhat", "spora-alloc/heap"]
devnet-prealloc = ["spora-consensus/devnet-prealloc"]
semaphore-trace = ["spora-utils/semaphore-trace"]
