[package]
name = "tondi-utxoindex"
description = "Tondi UTXO index"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
tondi-consensus-core.workspace = true
tondi-consensusmanager.workspace = true
tondi-core.workspace = true
tondi-database.workspace = true
tondi-hashes.workspace = true
tondi-index-core.workspace = true
tondi-utils.workspace = true
log.workspace = true
parking_lot.workspace = true
rocksdb.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tondi-consensus.workspace = true
rand = { workspace = true, features = ["small_rng"] }
