[package]
name = "spora-wrpc-example-subscriber"
description = "Spora wRPC subscription example"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
spora-consensus-core.workspace = true
spora-rpc-core.workspace = true
spora-wrpc-client.workspace = true
spora-notify.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
ctrlc.workspace = true
