#!/bin/bash
# Build script for RISC-V ELF fixtures
#
# Prerequisites:
# - Rust nightly toolchain with riscv64imac-unknown-none-elf target
# - Or: riscv64-unknown-elf-gcc toolchain
#
# Install Rust target:
#   rustup target add riscv64imac-unknown-none-elf

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../" && pwd)"
MANIFEST_FILE="${SCRIPT_DIR}/CODE_HASHES.blake3"
HASH_CACHE_FILE=""
FIXTURES=(
    always_success
    load_input_since
    load_header_timestamp
    load_dep_cell_data
    load_ecdsa_signature_hash
    secp256k1_lock_fixture
    secp256k1_blake3_lock
    timelock_absolute
    timelock_relative
    htlc_minimal
    htlc
)

echo "Building RISC-V ELF fixtures..."

# Check for Rust target
if rustup target list --installed | grep -q "riscv64imac-unknown-none-elf"; then
    echo "Using Rust riscv64imac-unknown-none-elf target"
    USE_RUST=1
else
    echo "Warning: riscv64imac-unknown-none-elf target not installed"
    echo "Install with: rustup target add riscv64imac-unknown-none-elf"
    echo ""
    echo "Alternatively, install RISC-V GCC toolchain:"
    echo "  brew install riscv-tools  # macOS"
    echo "  apt-get install gcc-riscv64-linux-gnu  # Ubuntu"
    exit 1
fi

cleanup() {
    if [ -n "$HASH_CACHE_FILE" ] && [ -f "$HASH_CACHE_FILE" ]; then
        rm -f "$HASH_CACHE_FILE"
    fi
}

trap cleanup EXIT

build_fixture() {
    local name="$1"
    local source_file="${name}.rs"
    local output_file="${name}.elf"
    
    # Check if source file exists
    if [ ! -f "$source_file" ]; then
        echo "Error: Source file not found: ${source_file}" >&2
        return 1
    fi
    
    echo "Building ${output_file}..."
    if ! rustc --edition 2021 \
        --target riscv64imac-unknown-none-elf \
        -C opt-level=3 \
        -o "$output_file" \
        "$source_file"; then
        echo "Error: Failed to build ${output_file}" >&2
        return 1
    fi
}

for fixture in "${FIXTURES[@]}"; do
    build_fixture "${fixture}"
done

echo ""
echo "Build complete!"
echo ""
HASH_TOOL=""
if command -v blake3sum >/dev/null 2>&1; then
    HASH_TOOL="blake3sum"
elif command -v b3sum >/dev/null 2>&1; then
    HASH_TOOL="b3sum"
else
    HASH_TOOL="cargo-fixture-hash"
fi

if [ "$HASH_TOOL" = "cargo-fixture-hash" ]; then
    HASH_CACHE_FILE="$(mktemp)"
    helper_args=()
    for fixture in "${FIXTURES[@]}"; do
        helper_args+=("${SCRIPT_DIR}/${fixture}.elf")
    done
    (
        cd "$REPO_ROOT"
        cargo run --quiet -p spora-exec --example fixture_hashes -- "${helper_args[@]}"
    ) > "$HASH_CACHE_FILE"
fi

calc_hash() {
    local file="$1"
    local file_path="$file"
    local file_name
    if [[ "$file_path" != /* ]]; then
        file_path="${SCRIPT_DIR}/${file_path}"
    fi
    file_name="$(basename "$file_path")"
    if [ "$HASH_TOOL" = "cargo-fixture-hash" ]; then
        awk -v target="$file_name" '$2 == target { print $1 }' "$HASH_CACHE_FILE"
    elif [ -n "$HASH_TOOL" ]; then
        ${HASH_TOOL} "${file_path}" | cut -d' ' -f1
    else
        return 1
    fi
}

print_hash() {
    local label="$1"
    local file="$2"
    local hash
    hash="$(calc_hash "$file")"
    if [ -n "$hash" ]; then
        echo "  ${label}: ${hash}"
    else
        echo "  ${label}: <hash unavailable>"
    fi
}

write_manifest() {
    {
        printf "# Generated by build_fixtures.sh (format: <blake3>  <elf>)\n"
        for fixture in "${FIXTURES[@]}"; do
            local file="${fixture}.elf"
            local hash
            hash="$(calc_hash "$file")"
            if [ -z "$hash" ]; then
                echo "failed to compute hash for ${file}" >&2
                return 1
            fi
            printf "%s  %s\n" "$hash" "$file"
        done
    } > "${MANIFEST_FILE}"
}

echo "Code hashes:"
for fixture in "${FIXTURES[@]}"; do
    print_hash "${fixture}" "${fixture}.elf"
done

write_manifest
echo ""
echo "Hash manifest written: ${MANIFEST_FILE}"
